---
#
# copy modified upgrade script
- name: Restart SOLR on s-solr002
  hosts: s-solr002.ec2.liblime.com
  tasks:

    - name: stop solr on s-solr002
      command: /etc/init.d/solr stop

    - name: start solr on s-solr002
      command: /etc/init.d/solr start
